training_pipeline_config:
  pipeline_name: Artifact
  artifact_dir: artifact

# artifact/data_ingestion/raw_data & ingested_Data /Train & Test
data_ingestion_config:
  data_base: Machine_learning
  collection_name: DATASET
  data_ingestion: data_ingestion
  raw_data_dir: raw_data
  ingested_dir: ingested_Data
  ingested_train_dir: Train
  ingested_test_dir: Test
#   
data_transformation_config:
  data_transformation_dir: data_transformation
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl
  feature_eng_file: fea_eng.pkl




